from __future__ import annotations

import csv
import sqlite3
from datetime import date, datetime
from pathlib import Path
from typing import Any, Callable

import psycopg
from psycopg.rows import dict_row


class DatabaseRow(dict[str, Any]):
    def __getitem__(self, key: str | int) -> Any:
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


class PostgresResult:
    def __init__(self, cursor: Any, returns_id: bool = False):
        self.cursor = cursor
        self.returns_id = returns_id

    @staticmethod
    def _row(row: dict[str, Any] | None) -> DatabaseRow | None:
        if row is None:
            return None
        values = {
            key: value.isoformat() if isinstance(value, (date, datetime)) else value
            for key, value in row.items()
        }
        return DatabaseRow(values)

    def fetchone(self) -> DatabaseRow | None:
        return self._row(self.cursor.fetchone())

    def fetchall(self) -> list[DatabaseRow]:
        return [self._row(row) for row in self.cursor.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())

    @property
    def lastrowid(self) -> int | None:
        if not self.returns_id:
            return None
        row = self.fetchone()
        return row["id"] if row else None


class DatabaseConnection:
    def __init__(self, connection: Any, is_postgres: bool):
        self.connection = connection
        self.is_postgres = is_postgres

    def execute(self, query: str, parameters: tuple[Any, ...] = ()) -> Any:
        if not self.is_postgres:
            return self.connection.execute(query, parameters)

        sql = query.replace("?", "%s")
        returns_id = sql.lstrip().lower().startswith("insert into customer_reviews")
        if returns_id and " returning " not in sql.lower():
            sql = sql.rstrip().rstrip(";") + " RETURNING id"
        cursor = self.connection.cursor()
        cursor.execute(sql, parameters)
        return PostgresResult(cursor, returns_id)

    def commit(self) -> None:
        self.connection.commit()

    def rollback(self) -> None:
        self.connection.rollback()

    def close(self) -> None:
        self.connection.close()


def connect_database(database_url: str | None, database_path: str) -> DatabaseConnection:
    if database_url:
        connection = psycopg.connect(
            database_url,
            row_factory=dict_row,
            prepare_threshold=None,
            connect_timeout=10,
            sslmode="require",
        )
        return DatabaseConnection(connection, is_postgres=True)

    Path(database_path).parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return DatabaseConnection(connection, is_postgres=False)


def _create_tables(connection: DatabaseConnection) -> None:
    if connection.is_postgres:
        connection.execute(
            """CREATE TABLE IF NOT EXISTS customer_reviews (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                review TEXT NOT NULL,
                review_date TEXT NOT NULL,
                source TEXT NOT NULL DEFAULT 'Other',
                sentiment TEXT NOT NULL CHECK (sentiment IN ('positive', 'neutral', 'negative')),
                score DOUBLE PRECISION NOT NULL CHECK (score >= -1 AND score <= 1),
                category TEXT NOT NULL DEFAULT 'General',
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"""
        )
        connection.execute("CREATE INDEX IF NOT EXISTS idx_reviews_date ON customer_reviews(review_date)")
        connection.execute("CREATE INDEX IF NOT EXISTS idx_reviews_sentiment ON customer_reviews(sentiment)")
        connection.execute(
            """CREATE TABLE IF NOT EXISTS app_users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"""
        )
        connection.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_username_lower ON app_users (LOWER(username))")
        return

    connection.execute(
        """CREATE TABLE IF NOT EXISTS customer_reviews (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            review TEXT NOT NULL,
            review_date TEXT NOT NULL,
            source TEXT NOT NULL DEFAULT 'Other',
            sentiment TEXT NOT NULL CHECK (sentiment IN ('positive', 'neutral', 'negative')),
            score REAL NOT NULL CHECK (score >= -1 AND score <= 1),
            category TEXT NOT NULL DEFAULT 'General',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )"""
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_reviews_date ON customer_reviews(review_date)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_reviews_sentiment ON customer_reviews(sentiment)")
    connection.execute(
        """CREATE TABLE IF NOT EXISTS app_users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL COLLATE NOCASE UNIQUE,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )"""
    )


def _insert_sample_rows(
    connection: DatabaseConnection,
    sample_file: Path,
    analyze_review: Callable[[str], dict[str, Any]],
) -> int:
    if not sample_file.exists():
        return 0
    with sample_file.open("r", encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream))
    inserted = 0
    for row in rows:
        text = (row.get("review") or row.get("text") or "").strip()
        if not text:
            continue
        result = analyze_review(text)
        cursor = connection.execute(
            "INSERT INTO customer_reviews (review, review_date, source, sentiment, score, category) VALUES (?, ?, ?, ?, ?, ?)",
            (
                text,
                normalize_date(row.get("date")),
                (row.get("source") or "Survey").strip(),
                result["sentiment"],
                result["score"],
                result["category"],
            ),
        )
        if connection.is_postgres:
            cursor.fetchone()
        inserted += 1
    return inserted


def normalize_date(value: str | None) -> str:
    if value:
        try:
            return datetime.fromisoformat(value.strip().replace("Z", "+00:00")).date().isoformat()
        except ValueError:
            pass
    return date.today().isoformat()


def initialize_database(
    database_url: str | None,
    database_path: str,
    sample_file: Path,
    analyze_review: Callable[[str], dict[str, Any]],
) -> None:
    connection = connect_database(database_url, database_path)
    _create_tables(connection)
    count = connection.execute("SELECT COUNT(*) FROM customer_reviews").fetchone()[0]
    if count == 0:
        _insert_sample_rows(connection, sample_file, analyze_review)
    connection.commit()
    connection.close()


def load_sample_data(
    database_url: str | None,
    database_path: str,
    sample_file: Path,
    analyze_review: Callable[[str], dict[str, Any]],
) -> int:
    connection = connect_database(database_url, database_path)
    _create_tables(connection)
    inserted = _insert_sample_rows(connection, sample_file, analyze_review)
    connection.commit()
    connection.close()
    return inserted
